### ISSUE TITLE
Must manually remove header from samples file

### ISSUE THREAD

**Issue by kdavies4** [jdherman/SALib#34]
The following error occurs when I run [step 4 of the Morris analysis](https://waterprogramming.wordpress.com/2013/09/23/method-of-morris-elementary-effects-using-salib/):

    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/local/lib/python2.7/dist-packages/SALib/analyze/morris.py", line 206, in <module>
        num_levels=args.levels, grid_jump=args.grid_jump)
      File "/usr/local/lib/python2.7/dist-packages/SALib/analyze/morris.py", line 33, in analyze
        X = np.loadtxt(input_file, delimiter=delim, ndmin=2)
      File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 848, in loadtxt
        items = [conv(val) for (conv, val) in zip(converters, vals)]
    ValueError: could not convert string to float: adCO_k

I must manually remove the first line (header row) of *my_samples_file.txt* to avoid the error.

**Comment by jdherman** [comment]
Thanks Kevin. Is the header row being added automatically by the library, or are you adding it in? Right now the file is being read with `np.loadtxt`, which I think will require a special argument for the number of header lines that isn't currently there.

What version of numpy/python is this? Thanks again for posting the issue.

**Comment by kdavies4** [comment]
Jon, I'm really sorry I bugged you about this. I looked more closely at my code (which I wrote before the holidays) and I'm actually writing that header.

**Comment by jdherman** [comment]
Ok great, no worries!
